Database:
  postgres:
    User:
      # If the user doesn't exist already, it is created
      Username: 'ztd_user'
      Password: 'ZTD_USER를_위한_새로운_강력한_비밀번호'
    Admin:
      Username: 'psg_admin' # docker-compose.yaml의 POSTGRES_USER와 일치해야 함
      Password: 'db_password.txt의_내용을_그대로_붙여넣기'